<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\Category;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Seeder;

class ArticleSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::first();
        $esp32Cat = Category::where('slug', 'esp32-arduino')->first();
        $iotCat   = Category::where('slug', 'iot-smart-device')->first();

        $articles = [
            [
                'title'       => 'Mengenal ESP32: Mikrokontroler WiFi & Bluetooth untuk IoT',
                'slug'        => 'mengenal-esp32-mikrokontroler-wifi-bluetooth-iot',
                'category_id' => $esp32Cat->id,
                'is_featured' => true,
                'tags'        => ['ESP32', 'IoT', 'WiFi', 'Bluetooth', 'Mikrokontroler'],
                'cover_image' => null,
                'seo_title'   => 'Mengenal ESP32: Panduan Lengkap Mikrokontroler WiFi Bluetooth',
                'seo_description' => 'Pelajari apa itu ESP32, spesifikasi lengkap, keunggulan, dan mengapa ESP32 menjadi pilihan utama untuk proyek IoT dan embedded system.',
                'body'        => $this->article1Body(),
            ],
            [
                'title'       => 'Cara Install Arduino IDE dan Setup ESP32 Board Manager',
                'slug'        => 'cara-install-arduino-ide-setup-esp32-board-manager',
                'category_id' => $esp32Cat->id,
                'is_featured' => true,
                'tags'        => ['ESP32', 'Arduino IDE', 'Setup', 'Tutorial'],
                'cover_image' => null,
                'seo_title'   => 'Tutorial Install Arduino IDE dan Setup ESP32 Board Manager 2026',
                'seo_description' => 'Panduan lengkap cara install Arduino IDE terbaru dan menambahkan ESP32 Board Manager untuk mulai pemrograman ESP32.',
                'body'        => $this->article2Body(),
            ],
            [
                'title'       => 'Blink LED dengan ESP32: Tutorial Pertama Embedded System',
                'slug'        => 'blink-led-esp32-tutorial-pertama-embedded-system',
                'category_id' => $esp32Cat->id,
                'is_featured' => false,
                'tags'        => ['ESP32', 'LED', 'GPIO', 'Tutorial', 'Pemula'],
                'cover_image' => null,
                'seo_title'   => 'Blink LED dengan ESP32 - Tutorial Pemula Embedded System',
                'seo_description' => 'Tutorial step-by-step membuat program Blink LED pertama dengan ESP32 menggunakan Arduino IDE. Cocok untuk pemula.',
                'body'        => $this->article3Body(),
            ],
            [
                'title'       => 'Menghubungkan ESP32 ke WiFi dan Kirim Data ke Server',
                'slug'        => 'menghubungkan-esp32-wifi-kirim-data-server',
                'category_id' => $iotCat->id,
                'is_featured' => false,
                'tags'        => ['ESP32', 'WiFi', 'IoT', 'HTTP', 'Server'],
                'cover_image' => null,
                'seo_title'   => 'Tutorial Menghubungkan ESP32 ke WiFi dan Kirim Data HTTP',
                'seo_description' => 'Pelajari cara menghubungkan ESP32 ke jaringan WiFi dan mengirim data sensor ke server menggunakan protokol HTTP dengan Arduino IDE.',
                'body'        => $this->article4Body(),
            ],
            [
                'title'       => 'Membaca Sensor DHT22 (Suhu & Kelembaban) dengan ESP32',
                'slug'        => 'membaca-sensor-dht22-suhu-kelembaban-esp32',
                'category_id' => $iotCat->id,
                'is_featured' => false,
                'tags'        => ['ESP32', 'DHT22', 'Sensor', 'IoT', 'Suhu'],
                'cover_image' => null,
                'seo_title'   => 'Tutorial Sensor DHT22 dengan ESP32 - Baca Suhu & Kelembaban',
                'seo_description' => 'Panduan lengkap cara membaca data suhu dan kelembaban dari sensor DHT22 menggunakan ESP32 dan library DHT sensor library.',
                'body'        => $this->article5Body(),
            ],
        ];

        foreach ($articles as $data) {
            $tags = $data['tags'];
            unset($data['tags']);

            $article = Article::create([
                ...$data,
                'user_id'      => $admin->id,
                'status'       => 'published',
                'published_at' => now()->subDays(rand(1, 30)),
                'excerpt'      => '', // auto-generated by model boot
            ]);

            // Attach tags
            $tagIds = [];
            foreach ($tags as $tagName) {
                $tag = Tag::where('name', $tagName)->first();
                if ($tag) $tagIds[] = $tag->id;
            }
            $article->tags()->sync($tagIds);
        }

        $this->command->info('✓ 5 artikel ESP32 berhasil dibuat!');
    }

    private function article1Body(): string
    {
        return <<<HTML
<h2>Apa itu ESP32?</h2>
<p>ESP32 adalah mikrokontroler serbaguna yang dikembangkan oleh <strong>Espressif Systems</strong> dari Tiongkok. Diluncurkan pertama kali pada tahun 2016, ESP32 langsung menjadi fenomena di dunia elektronik dan IoT karena menawarkan konektivitas WiFi dan Bluetooth dalam satu chip dengan harga yang sangat terjangkau.</p>

<p>Berbeda dengan Arduino Uno yang membutuhkan modul tambahan untuk konektivitas nirkabel, ESP32 sudah memiliki WiFi 802.11 b/g/n dan Bluetooth 4.2 (Classic + BLE) terintegrasi langsung di chipnya. Ini menjadikan ESP32 pilihan ideal untuk proyek IoT modern.</p>

<h2>Spesifikasi Teknis ESP32</h2>
<p>Berikut adalah spesifikasi lengkap chip ESP32 yang populer digunakan:</p>
<ul>
  <li><strong>Prosesor:</strong> Dual-core Xtensa LX6, up to 240 MHz</li>
  <li><strong>RAM:</strong> 520 KB SRAM internal</li>
  <li><strong>Flash:</strong> 4 MB (biasanya pada board development)</li>
  <li><strong>WiFi:</strong> 802.11 b/g/n (2.4 GHz)</li>
  <li><strong>Bluetooth:</strong> v4.2 BR/EDR dan BLE</li>
  <li><strong>GPIO:</strong> 34 pin programmable</li>
  <li><strong>ADC:</strong> 18 channel 12-bit SAR ADC</li>
  <li><strong>DAC:</strong> 2 channel 8-bit DAC</li>
  <li><strong>Tegangan operasi:</strong> 2.2V – 3.6V</li>
</ul>

<h2>Mengapa Memilih ESP32?</h2>
<p>Ada beberapa alasan kuat mengapa ESP32 menjadi pilihan utama para developer IoT dan hobbist embedded system:</p>

<h3>1. Harga Terjangkau</h3>
<p>Board development ESP32 seperti ESP32 DevKit V1 bisa didapat dengan harga mulai dari Rp 30.000 - Rp 80.000 di marketplace lokal. Bandingkan dengan Arduino Uno + modul WiFi yang bisa mencapai Rp 150.000+.</p>

<h3>2. Dual-Core Processing</h3>
<p>Dengan dua core CPU, ESP32 bisa menangani task secara paralel. Misalnya, satu core untuk membaca sensor, sementara core lain menangani komunikasi WiFi.</p>

<h3>3. Konektivitas Lengkap</h3>
<p>WiFi dan Bluetooth terintegrasi memungkinkan ESP32 berkomunikasi dengan smartphone, cloud, dan perangkat lain tanpa hardware tambahan.</p>

<h2>Perbandingan ESP32 vs ESP8266 vs Arduino</h2>
<p>Sebelum memilih mikrokontroler, penting memahami perbedaannya:</p>
<ul>
  <li><strong>Arduino Uno:</strong> Cocok untuk belajar dasar, tidak ada WiFi/Bluetooth built-in</li>
  <li><strong>ESP8266:</strong> Ada WiFi, single-core, GPIO lebih sedikit, lebih murah dari ESP32</li>
  <li><strong>ESP32:</strong> Terbaik untuk IoT lengkap, dual-core, WiFi + Bluetooth, GPIO banyak</li>
</ul>

<h2>Memulai dengan ESP32</h2>
<p>Untuk mulai belajar ESP32, yang kamu butuhkan:</p>
<ol>
  <li>Board ESP32 DevKit V1 atau sejenisnya</li>
  <li>Kabel USB micro-B atau USB-C (tergantung board)</li>
  <li>Laptop/PC dengan Arduino IDE terinstall</li>
  <li>Koneksi internet untuk download library</li>
</ol>

<p>Pada artikel selanjutnya, kita akan belajar cara <strong>menginstall Arduino IDE</strong> dan melakukan setup ESP32 Board Manager agar siap diprogram.</p>

<blockquote>
  <p><strong>Tips:</strong> Beli ESP32 dari toko terpercaya dan pastikan mendapatkan board yang genuine. Board palsu/kualitas rendah sering menyebabkan masalah koneksi dan tidak stabil.</p>
</blockquote>
HTML;
    }

    private function article2Body(): string
    {
        return <<<HTML
<h2>Pendahuluan</h2>
<p>Sebelum bisa memprogram ESP32, kita perlu menginstall Arduino IDE dan menambahkan support untuk ESP32. Artikel ini akan memandu kamu step-by-step dari awal hingga ESP32 siap diprogram.</p>

<h2>Langkah 1: Download Arduino IDE</h2>
<p>Arduino IDE adalah software yang digunakan untuk menulis dan meng-upload program ke mikrokontroler. Download versi terbaru dari website resmi:</p>
<ol>
  <li>Buka browser dan pergi ke <strong>arduino.cc/en/software</strong></li>
  <li>Pilih versi sesuai OS kamu (Windows, Mac, atau Linux)</li>
  <li>Download file installer (.exe untuk Windows)</li>
  <li>Install seperti biasa, ikuti wizard instalasi</li>
</ol>

<h2>Langkah 2: Tambahkan ESP32 Board Manager URL</h2>
<p>Setelah Arduino IDE terinstall, kita perlu menambahkan URL untuk Board Manager ESP32:</p>
<ol>
  <li>Buka Arduino IDE</li>
  <li>Klik menu <strong>File → Preferences</strong></li>
  <li>Di bagian <em>"Additional boards manager URLs"</em>, tambahkan URL berikut:</li>
</ol>

<pre><code class="language-text">https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json</code></pre>

<ol start="4">
  <li>Klik OK untuk menyimpan</li>
</ol>

<h2>Langkah 3: Install ESP32 via Board Manager</h2>
<p>Setelah menambahkan URL, kita install board ESP32:</p>
<ol>
  <li>Klik menu <strong>Tools → Board → Boards Manager</strong></li>
  <li>Di kolom pencarian, ketik <strong>"esp32"</strong></li>
  <li>Pilih <em>"esp32 by Espressif Systems"</em></li>
  <li>Klik tombol <strong>Install</strong> dan tunggu prosesnya selesai</li>
</ol>
<p>Proses instalasi membutuhkan koneksi internet dan bisa memakan waktu 5-10 menit tergantung kecepatan internet.</p>

<h2>Langkah 4: Install Driver USB</h2>
<p>ESP32 DevKit biasanya menggunakan chip CH340 atau CP2102 untuk komunikasi USB. Jika board tidak terdeteksi, install driver yang sesuai:</p>
<ul>
  <li><strong>CH340:</strong> Download dari <em>wch.cn/downloads/CH341SER_EXE.html</em></li>
  <li><strong>CP2102:</strong> Download dari <em>silabs.com/developers/usb-to-uart-bridge-vcp-drivers</em></li>
</ul>

<h2>Langkah 5: Test Koneksi ESP32</h2>
<p>Setelah semua terinstall, test koneksi ESP32:</p>
<ol>
  <li>Hubungkan ESP32 ke laptop via kabel USB</li>
  <li>Di Arduino IDE, pilih <strong>Tools → Board → ESP32 Arduino → ESP32 Dev Module</strong></li>
  <li>Pilih port yang sesuai di <strong>Tools → Port</strong> (biasanya COM3, COM4, dsb.)</li>
  <li>Upload contoh program: <strong>File → Examples → 01.Basics → Blink</strong></li>
</ol>

<h2>Contoh Program Pertama: Hello World</h2>
<p>Mari kita test dengan program sederhana yang menampilkan teks di Serial Monitor:</p>

<pre><code class="language-arduino">void setup() {
  Serial.begin(115200);
  Serial.println("Halo dari ESP32!");
}

void loop() {
  Serial.println("Koding Indonesia - ESP32 siap digunakan!");
  delay(1000);
}</code></pre>

<p>Upload program ini ke ESP32, kemudian buka <strong>Tools → Serial Monitor</strong> dengan baud rate <em>115200</em>. Kamu akan melihat pesan yang dicetak setiap detik.</p>

<blockquote>
  <p><strong>Masalah Umum:</strong> Jika gagal upload, tekan dan tahan tombol BOOT pada ESP32 saat proses upload dimulai, kemudian lepaskan ketika muncul teks "Connecting..." di output.</p>
</blockquote>
HTML;
    }

    private function article3Body(): string
    {
        return <<<HTML
<h2>Program Pertama: Blink LED</h2>
<p>Blink LED adalah "Hello World"-nya dunia embedded system. Pada tutorial ini, kita akan membuat LED bawaan ESP32 (built-in LED) berkedip setiap 1 detik menggunakan Arduino IDE.</p>

<h2>Apa itu GPIO?</h2>
<p><strong>GPIO</strong> (General Purpose Input/Output) adalah pin pada mikrokontroler yang bisa diprogram sebagai input atau output. ESP32 memiliki 34 pin GPIO yang masing-masing bisa digunakan untuk berbagai fungsi.</p>
<p>Built-in LED pada ESP32 DevKit biasanya terhubung ke pin <strong>GPIO 2</strong>. Namun ini bisa berbeda tergantung versi board yang kamu gunakan.</p>

<h2>Kode Program Blink LED</h2>
<p>Berikut adalah kode lengkap untuk membuat LED berkedip:</p>

<pre><code class="language-arduino">// Mendefinisikan pin LED
#define LED_PIN 2

void setup() {
  // Set pin LED sebagai OUTPUT
  pinMode(LED_PIN, OUTPUT);
  
  // Mulai Serial Monitor untuk debugging
  Serial.begin(115200);
  Serial.println("Program Blink LED ESP32 dimulai!");
}

void loop() {
  // Nyalakan LED
  digitalWrite(LED_PIN, HIGH);
  Serial.println("LED ON");
  delay(1000);  // Tunggu 1 detik
  
  // Matikan LED
  digitalWrite(LED_PIN, LOW);
  Serial.println("LED OFF");
  delay(1000);  // Tunggu 1 detik
}</code></pre>

<h2>Penjelasan Kode</h2>
<h3>setup() Function</h3>
<p>Fungsi <code>setup()</code> hanya dijalankan SEKALI saat ESP32 pertama kali dinyalakan atau direset. Di sini kita:</p>
<ul>
  <li><code>pinMode(LED_PIN, OUTPUT)</code> — Mengatur pin LED sebagai output</li>
  <li><code>Serial.begin(115200)</code> — Menginisialisasi komunikasi serial dengan baud rate 115200</li>
</ul>

<h3>loop() Function</h3>
<p>Fungsi <code>loop()</code> dijalankan BERULANG-ULANG selamanya setelah <code>setup()</code> selesai. Di sini kita:</p>
<ul>
  <li><code>digitalWrite(LED_PIN, HIGH)</code> — Memberikan tegangan ke pin LED (LED menyala)</li>
  <li><code>delay(1000)</code> — Menunggu 1000 milidetik (1 detik)</li>
  <li><code>digitalWrite(LED_PIN, LOW)</code> — Mematikan tegangan di pin LED (LED padam)</li>
</ul>

<h2>Cara Upload Program</h2>
<ol>
  <li>Salin kode di atas ke Arduino IDE</li>
  <li>Pastikan board sudah dipilih: <strong>Tools → Board → ESP32 Arduino → ESP32 Dev Module</strong></li>
  <li>Pilih port yang benar di <strong>Tools → Port</strong></li>
  <li>Klik tombol <strong>Upload</strong> (panah ke kanan)</li>
  <li>Tunggu hingga muncul "Done uploading"</li>
</ol>

<h2>Modifikasi: Blink dengan Kecepatan Berbeda</h2>
<p>Coba eksperimen dengan mengubah nilai delay untuk kecepatan kedip yang berbeda:</p>

<pre><code class="language-arduino">void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(100);   // Cepat: 100ms
  
  digitalWrite(LED_PIN, LOW);
  delay(100);
}</code></pre>

<p>Dengan delay 100ms, LED akan berkedip 5 kali lebih cepat dari sebelumnya!</p>

<blockquote>
  <p><strong>Tantangan:</strong> Modifikasi program agar LED berkedip dengan pola SOS morse code: 3 kedipan cepat, 3 kedipan lambat, 3 kedipan cepat.</p>
</blockquote>
HTML;
    }

    private function article4Body(): string
    {
        return <<<HTML
<h2>Pendahuluan</h2>
<p>Salah satu keunggulan utama ESP32 adalah kemampuannya terhubung ke WiFi. Pada tutorial ini, kita akan belajar cara menghubungkan ESP32 ke jaringan WiFi dan mengirim data ke server menggunakan protokol HTTP.</p>

<h2>Library yang Digunakan</h2>
<p>Untuk koneksi WiFi, ESP32 sudah memiliki library bawaan <code>WiFi.h</code> yang sudah termasuk saat menginstall ESP32 Board Manager. Untuk HTTP request, kita akan menggunakan library <code>HTTPClient.h</code>.</p>

<h2>Menghubungkan ESP32 ke WiFi</h2>
<p>Berikut adalah kode dasar untuk menghubungkan ESP32 ke jaringan WiFi:</p>

<pre><code class="language-arduino">#include &lt;WiFi.h&gt;

// Ganti dengan SSID dan password WiFi kamu
const char* ssid = "NamaWiFiKamu";
const char* password = "PasswordWiFiKamu";

void setup() {
  Serial.begin(115200);
  
  // Mulai koneksi WiFi
  WiFi.begin(ssid, password);
  Serial.print("Menghubungkan ke WiFi");
  
  // Tunggu hingga terhubung
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  
  Serial.println("\nTerhubung ke WiFi!");
  Serial.print("IP Address: ");
  Serial.println(WiFi.localIP());
}

void loop() {
  // Cek status koneksi
  if (WiFi.status() == WL_CONNECTED) {
    Serial.println("WiFi: Terhubung");
  } else {
    Serial.println("WiFi: Terputus, mencoba reconnect...");
    WiFi.reconnect();
  }
  delay(5000);
}</code></pre>

<h2>Mengirim Data ke Server (HTTP GET)</h2>
<p>Setelah terhubung ke WiFi, kita bisa mengirim data ke server menggunakan HTTP request:</p>

<pre><code class="language-arduino">#include &lt;WiFi.h&gt;
#include &lt;HTTPClient.h&gt;

const char* ssid = "NamaWiFiKamu";
const char* password = "PasswordWiFiKamu";
const char* serverURL = "http://api.example.com/data";

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\nWiFi terhubung!");
}

void loop() {
  if (WiFi.status() == WL_CONNECTED) {
    HTTPClient http;
    
    // Buat request dengan parameter
    String url = String(serverURL) + "?suhu=25.5&kelembaban=70";
    http.begin(url);
    
    int httpCode = http.GET();
    
    if (httpCode > 0) {
      Serial.print("HTTP Code: ");
      Serial.println(httpCode);
      
      if (httpCode == HTTP_CODE_OK) {
        String payload = http.getString();
        Serial.println("Response: " + payload);
      }
    } else {
      Serial.print("Error: ");
      Serial.println(http.errorToString(httpCode));
    }
    
    http.end();
  }
  
  delay(10000); // Kirim data setiap 10 detik
}</code></pre>

<h2>Mengirim Data dengan HTTP POST</h2>
<p>Untuk mengirim data yang lebih kompleks, gunakan HTTP POST dengan format JSON:</p>

<pre><code class="language-arduino">void kirimDataJSON(float suhu, float kelembaban) {
  HTTPClient http;
  http.begin(serverURL);
  http.addHeader("Content-Type", "application/json");
  
  // Buat JSON string
  String jsonData = "{\"suhu\":" + String(suhu) + 
                    ",\"kelembaban\":" + String(kelembaban) + 
                    ",\"device\":\"ESP32-001\"}";
  
  int httpCode = http.POST(jsonData);
  
  if (httpCode == 200) {
    Serial.println("Data berhasil dikirim!");
  }
  
  http.end();
}</code></pre>

<blockquote>
  <p><strong>Penting:</strong> Jangan hardcode password WiFi di dalam kode yang akan dipublish ke repository publik. Gunakan file konfigurasi terpisah atau mekanisme provisioning seperti WiFiManager.</p>
</blockquote>
HTML;
    }

    private function article5Body(): string
    {
        return <<<HTML
<h2>Pendahuluan</h2>
<p>DHT22 (juga dikenal sebagai AM2302) adalah sensor digital yang bisa mengukur suhu dan kelembaban udara sekaligus. Sensor ini sangat populer dalam proyek IoT karena mudah digunakan dan memiliki akurasi yang cukup baik untuk kebanyakan aplikasi.</p>

<h2>Spesifikasi DHT22</h2>
<ul>
  <li><strong>Range suhu:</strong> -40°C hingga +80°C</li>
  <li><strong>Akurasi suhu:</strong> ±0.5°C</li>
  <li><strong>Range kelembaban:</strong> 0% hingga 100% RH</li>
  <li><strong>Akurasi kelembaban:</strong> ±2-5% RH</li>
  <li><strong>Interface:</strong> Single-wire digital</li>
  <li><strong>Tegangan:</strong> 3.3V atau 5V</li>
</ul>

<h2>Wiring / Koneksi Hardware</h2>
<p>Koneksi DHT22 ke ESP32 sangat sederhana:</p>
<ul>
  <li><strong>VCC</strong> (pin 1) → 3.3V ESP32</li>
  <li><strong>DATA</strong> (pin 2) → GPIO 4 ESP32 (+ resistor 10kΩ ke VCC)</li>
  <li><strong>GND</strong> (pin 4) → GND ESP32</li>
</ul>
<p>Resistor pull-up 10kΩ antara pin DATA dan VCC sangat penting untuk komunikasi yang stabil!</p>

<h2>Install Library DHT</h2>
<p>Kita perlu menginstall library DHT sensor dari Adafruit:</p>
<ol>
  <li>Buka Arduino IDE</li>
  <li>Klik <strong>Sketch → Include Library → Manage Libraries</strong></li>
  <li>Cari <strong>"DHT sensor library"</strong> oleh Adafruit</li>
  <li>Klik Install (juga install dependency "Adafruit Unified Sensor" jika diminta)</li>
</ol>

<h2>Kode Program: Baca Suhu dan Kelembaban</h2>

<pre><code class="language-arduino">#include &lt;DHT.h&gt;

#define DHT_PIN 4        // Pin data DHT22 terhubung ke GPIO 4
#define DHT_TYPE DHT22   // Tipe sensor: DHT22

DHT dht(DHT_PIN, DHT_TYPE);

void setup() {
  Serial.begin(115200);
  dht.begin();
  Serial.println("DHT22 Sensor Siap!");
}

void loop() {
  // Tunggu 2 detik antara pembacaan (DHT22 butuh waktu)
  delay(2000);
  
  // Baca kelembaban
  float kelembaban = dht.readHumidity();
  
  // Baca suhu dalam Celsius
  float suhu = dht.readTemperature();
  
  // Baca suhu dalam Fahrenheit
  float suhuF = dht.readTemperature(true);
  
  // Cek apakah pembacaan berhasil
  if (isnan(kelembaban) || isnan(suhu)) {
    Serial.println("Gagal membaca dari sensor DHT22!");
    return;
  }
  
  // Hitung Heat Index
  float heatIndex = dht.computeHeatIndex(suhu, kelembaban, false);
  
  // Tampilkan hasil
  Serial.println("=== Pembacaan DHT22 ===");
  Serial.print("Kelembaban: ");
  Serial.print(kelembaban);
  Serial.println(" %");
  
  Serial.print("Suhu: ");
  Serial.print(suhu);
  Serial.println(" °C");
  
  Serial.print("Suhu: ");
  Serial.print(suhuF);
  Serial.println(" °F");
  
  Serial.print("Heat Index: ");
  Serial.print(heatIndex);
  Serial.println(" °C");
  Serial.println();
}</code></pre>

<h2>Kirim Data DHT22 ke Server via WiFi</h2>
<p>Kombinasikan dengan WiFi untuk mengirim data sensor ke server:</p>

<pre><code class="language-arduino">#include &lt;WiFi.h&gt;
#include &lt;HTTPClient.h&gt;
#include &lt;DHT.h&gt;

#define DHT_PIN 4
#define DHT_TYPE DHT22

const char* ssid = "WiFiKamu";
const char* password = "PasswordKamu";

DHT dht(DHT_PIN, DHT_TYPE);

void setup() {
  Serial.begin(115200);
  dht.begin();
  
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
  }
  Serial.println("WiFi terhubung!");
}

void loop() {
  delay(10000); // Baca dan kirim setiap 10 detik
  
  float suhu = dht.readTemperature();
  float kelembaban = dht.readHumidity();
  
  if (!isnan(suhu) && !isnan(kelembaban)) {
    HTTPClient http;
    http.begin("http://api.server.com/sensor");
    http.addHeader("Content-Type", "application/json");
    
    String payload = "{\"suhu\":" + String(suhu, 2) + 
                     ",\"kelembaban\":" + String(kelembaban, 2) + "}";
    
    int code = http.POST(payload);
    Serial.println(code == 200 ? "Data terkirim!" : "Gagal kirim data");
    http.end();
  }
}</code></pre>

<blockquote>
  <p><strong>Tips Troubleshooting:</strong> Jika pembacaan selalu NaN (Not a Number), periksa koneksi kabel dan pastikan resistor pull-up 10kΩ terpasang dengan benar. DHT22 sensitif terhadap noise listrik, jauhkan dari sumber interferensi.</p>
</blockquote>

<h2>Langkah Selanjutnya</h2>
<ul>
  <li><a href="/artikel/membuat-web-server-esp32-monitoring-sensor-dht22">Web Server ESP32 + DHT22</a> — tampilkan data di browser</li>
  <li><a href="/artikel/memahami-mqtt-esp32-kirim-data-sensor-broker">Publish data sensor via MQTT</a></li>
  <li><strong>Seri 2:</strong> <a href="/artikel/i2c-esp32-sensor-bme280-suhu-tekanan-mqtt">Sensor BME280 via I2C</a> — upgrade akurasi + tekanan udara</li>
</ul>
HTML;
    }
}
